# Chapter 3 Challenge
# - Push trigger
# - Environment variable for artifact name
# - one job with two steps
#     - action/checkout
#     - actions/upload-artifact
name: artifacts
on: push
env: 
  ARTIFACT_NAME: 'example_artifact'

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create-file
        run: |
          touch ${{ env.ARTIFACT_NAME }}.txt
          echo "This is a test artifact" > ${{ env.ARTIFACT_NAME }}.txt
      - name: upload
        uses: actions/upload-artifact@v3.1.0
        with:
          name: example_artifact
          path: ./${{ env.ARTIFACT_NAME }}.txt
