# Chapter 2 challenge
# - Push trigger
# - Four jobs
#     - each prints date
#     - Job 1 - ubuntu-latest
#     - Job 2 - windows-latest
#     - Job 3 - macos-latest
#     - Job 4 - depends on jobs 1, 2, and 3
name: date
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        uses: actions/checkout@v2
      - name: Step2
        run: date
  job2:
    runs-on: windows-latest
    steps:
      - name: Step1
        uses: actions/checkout@v2
      - name: Step2
        run: Get-Date
  job3:
    runs-on: macos-latest
    steps:
      - name: Step1
        uses: actions/checkout@v2
      - name: Step2
        run: date
  job4:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: Step1
        uses: actions/checkout@v2
      - name: Step2
        run: date
